### ISSUE TITLE
Clarify that motor_move(_voltage)/Motor::move(_voltage) do not respect brake mode

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros-docs#103]
I've noticed this has caused some confusion, and could be clarified in the docs by adding a note to each of the relevant functions that they will not respect brake modes.

This could also spill over to the kernel in two ways:
1. Add equivalent notes to the function documentation comments
2. Add a brake function that will stop the motor using a function that respects brake mode

**Comment by WillXuCodes** [comment]
Note: As an alternative to this we could just include this information with PROS 4 in the header file and let doxygen do the work.
