### ISSUE TITLE
Some ADI sensors are missing from the docs

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-docs#106]
`ADIPotentiometer`, `ADILineSensor`, `ADILightSensor`, and `ADIAccelerometer` are not documented, except for in a note here: https://pros.cs.purdue.edu/v5/api/cpp/adi.html#pros-adianalogin

**Comment by edjubuh** [comment]
I don't think you understand. They are **literally** ADIAnalogIn objects as well:
https://github.com/purduesigbots/pros/blob/bc1f4cb76e271603176069c5d46c14cae2032d64/include/pros/adi.hpp#L205-L208

On a slightly more serious note, we're considering them deprecated now that the ADI itself makes no formal distinction between them. It did once upon a time for reasons I'm not entirely sure of, but it no longer does. We kept it around for backwards compatibility reasons that are moot now that we're well out of beta phase.

**Comment by Octogonapus** [comment]
I know. But people don't know they exist. I opened this issue because Jonathan and I were helping someone who got confused.

**Comment by kunwarsahni01** [comment]
See #179
