### ISSUE TITLE
Line Sensor C++ tutorial uses the wrong class type

### ISSUE THREAD

**Issue by baylessj** [purduesigbots/pros-docs#107]
https://pros.cs.purdue.edu/v5/tutorials/topical/adi.html?highlight=line%20sensor#line-tracker

The example code in the linked portion of the tutorial is incorrect.

**Comment by kunwarsahni01** [comment]
I am assuming you think this should be changed to `ADIAnalogIn`?

**Comment by baylessj** [comment]
Correct, sorry for the lack of explanation in the issue's original comment.

After looking at the C example again, it appears that it is still using PROS 2 syntax rather than PROS 3. This should be updated too.

**Comment by kunwarsahni01** [comment]
Check out #179
