### ISSUE TITLE
Pros 2 download link on website doesnt work

### ISSUE THREAD

**Issue by Samuel12321** [purduesigbots/pros-docs#114]
The pros 2 download link is broken it causes a 404 error

**Comment by edjubuh** [comment]
We'd appreciate a PR on the appropriate dead link

**Comment by HotelCalifornia** [comment]
#113 ?

**Comment by Samuel12321** [comment]
![Annotation 2019-03-27 202322](https://user-images.githubusercontent.com/35312698/55057534-57eac700-50ce-11e9-83c7-139938836ffd.jpg)

**Leads to this page:**

![Annotation 2019-03-27 202406](https://user-images.githubusercontent.com/35312698/55057533-57eac700-50ce-11e9-9207-39e649bc1d71.jpg)

**Comment by Octogonapus** [comment]
I just tried this and it works, so I'm closing this unless others have problems.

**Comment by Samuel12321** [comment]
Just tried it again on 3 different laptops, still broken

**Comment by Octogonapus** [comment]
Ok... though I would like someone else to confirm this

**Comment by HotelCalifornia** [comment]
https://github.com/purduesigbots/pros-docs/blob/4e44911bbe66bf2647f7c83036282af23aa89bff/home/_templates/index.html#L109

based on that, everything should be fine, but as we can see, it's definitely the wrong link:

![](https://puu.sh/Dk1Xp/9b99b83eea.png)

in other words, it must nut be using home/_templates/index.html or something.

@Samuel12321 just so you know, PROS 3.x is fully backwards compatible with the VEX Cortex, so there's not really any reason you should need to download PROS specifically for the Cortex anymore

**Comment by Samuel12321** [comment]
Thanks, i do use pros 3 but was just just trialing 2 to see if it fixed another problem i had, and noticed link was broken.

**Comment by Samuel12321** [comment]
just tried the link above for testing purposes and it does work, but the pros for cortex link on the website still does not work.
Appears to be taking me to this website?https://github.com/purduesigbots/pros/releases/download/3.1.6/pros-win.exe

**Comment by HotelCalifornia** [comment]
> Still appears to be taking me to this website?https://github.com/purduesigbots/pros/releases/download/3.1.6/pros-win.exe
> as seen in the photo i provided above

yeah, that's what I was getting at in my comment. I'm not sure where that link is coming from

**Comment by HotelCalifornia** [comment]
just kidding, I found it

https://github.com/purduesigbots/pros-docs/blob/8bf45602772bfbebea486e2d27fbd37c660ff5f5/home/_static/js/script.js#L12

**Comment by kunwarsahni01** [comment]
This doesn't appear to exist anymore in the current version of the website.
