### ISSUE TITLE
Vision::create_color_code signature doesn't document default parameters

### ISSUE THREAD

**Issue by kdcrafter** [purduesigbots/pros-docs#119]
In the Vision Sensor C++ API documentation, the create_color_code() example is slightly off. The example has the line of code: 
`pros::vision_color_code_t code1 = vis.create_color_code(EXAMPLE_SIG, OTHER_SIG);`. 
However, it should be 
`pros::vision_color_code_t code1 = vis.create_color_code(EXAMPLE_SIG, OTHER_SIG, 0, 0, 0);` 
as less than 5 signatures are apart of the color in this example.

**Comment by HotelCalifornia** [comment]
Hi, thanks for the report. The `Vision::create_color_code` function actually provides default values for all the parameters after the second one:

https://github.com/purduesigbots/pros/blob/59d92c3194af74cc59be7575fb92d0f04785093c/include/pros/vision.hpp#L105-L107

That said, it seems like we neglected to include this fact in the documentation for the prototype
