### ISSUE TITLE
Failed to build casued by ablog

### ISSUE THREAD

**Issue by berberman** [purduesigbots/pros-docs#136]
I called `make v5` in my console, and I got this output:
```
Traceback (most recent call last):
  File "/home/berberman/.local/lib/python3.7/site-packages/ablog/post.py", line 579, in generate_atom_feeds
    raise StopIteration
StopIteration
```
Here is the code snippet from line 569 to 580 of `post.py`:
```python
def generate_atom_feeds(app):
    """Generate archive pages for all posts, categories, tags, authors, and
    drafts."""

    if not ablog.builder_support(app):
        return

    blog = Blog(app)

    url = blog.blog_baseurl
    if not url:
        raise StopIteration

```
I think dependencies used in building had been installed properly, seemingly `blog_baseurl` led to the mistake. I appended `blog_baseurl = 'blog'` at the end of `conf.py`, then I got correct html files.

Is this the right way to deal with this problem?

**Comment by kunwarsahni01** [comment]
I had this issue a while back and using a virtual environment for building the docs solved this problem for me.
