### ISSUE TITLE
Controller Inputs and Outputs lack of Code

### ISSUE THREAD

**Issue by acetousk** [purduesigbots/pros-docs#137]
### Description

In [this](https://pros.cs.purdue.edu/v5/okapi/tutorials/concepts/controller-io.html) it says *Using Controller Inputs and Outputs is quite simple* however, they aren't simple to people who haven't written and understand exactly how they work. To make this more understandable it would be helpful to add some example code in this tutorial. 

### Steps to Reproduce

1. Go to [this](https://pros.cs.purdue.edu/v5/okapi/tutorials/concepts/controller-io.html)
2. Read through it pretending to not have a perfect understanding of the code.

**Expected behavior:** Some kind of code that explains how *simple* the controller io is.

**Actual behavior:** No such code exists.

### Versions

```
--------  -----------  -------------
kernel    3.1.6        pros-mainline
okapilib  4.0.0-beta8  local```

**Comment by Octogonapus** [comment]
Closing this because OkapiLib's documentation has moved.
