### ISSUE TITLE
windows installer path is not correct

### ISSUE THREAD

**Issue by dnj12345** [purduesigbots/pros-docs#141]
Hi,
The 'Download Pros For Cortex' link on the main home page is not correct. I am getting a 404 not found error on both mac and windows. When I click download on this page https://pros.cs.purdue.edu/cortex/getting-started/windows.html, I am taken to https://github.com/purduesigbots/pros/releases/tag/3.1.6 which is again not the correct this. Looks like this is the only one that seems to work: https://github.com/purduesigbots/pros/releases/tag/2.12.2

I got to this link from: https://github.com/purduesigbots/pros-atom ---> https://github.com/purduesigbots/pros/releases   ---> https://github.com/purduesigbots/pros/releases/tag/2.12.2

**Comment by dnj12345** [comment]
Thanks for your help. I uninstalled everything and reinstall pros per the instruction on the link you sent. However, when I got to compile my project, I get the following error and the window is stuck. ctrl-c etc won't kill it. My project is the very first starter project from clawbot tutorial.
 
C:\Users\xxxxx\My Documents\pros\myTestProject>prosv5 make
ERROR - __main__:main - [WinError 3] The system cannot find the path specified
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\lib\subprocess.py", line 709, in __init__
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\lib\subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 3] The system cannot find the path specified
We detected something went wrong! Do you want to send a report? [y/N]: y
Sending bug report.
Want to get updates? Visit https://pros.cs.purdue.edu/report.html?event=a1992362897146ef8350717c2fc9d275

**Comment by dnj12345** [comment]
Thanks. I've followed your instructions. 64-bit installation worked without any issues. The link you sent never talks about installing the pros3 package in atom. Perhaps you could add that. 

Now I am running into the issue where the terminal does not open when I try to build or simply say select open terminal. Not sure how to fix. Googling it, folks are suggesting its a firewall issue. Need to figure that out. :(

**Comment by HotelCalifornia** [comment]
> The link you sent never talks about installing the pros3 package in atom. Perhaps you could add that.

Again.... You don't need to install anything manually

> Now I am running into the issue where the terminal does not open when I try to build or simply say select open terminal. When I press 'ctrl + ~' it opens up what seems like a terminal, but I never the prompt where I can type something, it just hangs with a blinking prompt

Are you talking about the PROS terminal, which opens a serial connection to your microcontroller? Or a regular console window?

**Comment by dnj12345** [comment]
Are you saying I shouldn't have to install pros-atom3 packing in atom? When I did not install, I did not see any PROS buttons etc Only, after installing pros-atom3 package in atom dis I see those buttons. BTW, this was a fresh install of atom and prosv5 software.

Yes, I am talking about PROS terminal. When I press the build pros button, I expected a window to show up where is shows me the project being build and report any errors. That is not happening. I've raised an issue:

https://github.com/purduesigbots/pros-atom/issues/75

haven't received any response yet.

**Comment by HotelCalifornia** [comment]
> Are you saying I shouldn't have to install pros-atom3 packing in atom? When I did not install, I did not see any PROS buttons etc Only, after installing pros-atom3 package in atom dis I see those buttons. BTW, this was a fresh install of atom and prosv5 software.

Yes, that is what I'm saying. We have a package named pros-bootstrapper (version 0.0.12) which is included by default in the PROS Editor and should install all dependent packages required to run the ecosystem properly.
