### ISSUE TITLE
Enum Value Table Error

### ISSUE THREAD

**Issue by SomewhatAccurate** [purduesigbots/pros-docs#149]
Under /v5/api/cpp/motors.rst  in section pros::motor_fault_e_t . [link](https://github.com/purduesigbots/pros-docs/blob/master/v5/api/cpp/motors.rst#id61)

The table showing the enum value meanings for fault bits has the first value listed properly, but the next 3 spots on the table appear to be copied from the motor_brake_mode_e_t enum value table, and the final value for the motor_fault is not listed.

should be something akin to:

Value 

pros::E_MOTOR_FAULT_NO_FAULTS                  | No faults
pros::E_MOTOR_FAULT_MOTOR_OVER_TEMP   | Motor temperature over set limit
pros::E_MOTOR_FAULT_DRIVER_FAULT             | Motor H-Bridge fault
pros::E_MOTOR_FAULT_OVER_CURRENT          | Motor current over set limit
pros::E_MOTOR_FAULT_DRV_OVER_CURRENT  | Motor H-Bridge over current limit

**Comment by SomewhatAccurate** [comment]
im fairly new to editing on git hub like this, so apologize if I'm going against convention / not styling it all neat enough. Ill probably be adding these issues fairly often as there are a few errors here and there Ive spotted on the documentation and I believe would be greatly beneficial to get sorted out. Thanks ahead for when yall see this.

**Comment by HotelCalifornia** [comment]
see #148 for the proposed change
