### ISSUE TITLE
pros-cli-v5 can't be found on some prs

### ISSUE THREAD

**Issue by nathan-moore** [purduesigbots/pros-docs#156]
In #155 the build failed due to not being able to install pros-cli-v5. It seems to be intermittent, however, as #154 succeeded.

**Comment by HotelCalifornia** [comment]
This is an issue with azure artifact feeds that we're currently investigating.

**Comment by WillXuCodes** [comment]
With us moving to doxygen with the coming of PROS 4, I don't think this will be an issue anymore.

**Comment by nathan-moore** [comment]
This effects more then pros-docs. For example, this is the issue tracking outside contributer's ci not running on the pros repo.

**Comment by kunwarsahni01** [comment]
This can be solved by someone inside of the azure organization commenting `/azp run` on any pr.
