### ISSUE TITLE
install PROS fail, prompt: java not installed

### ISSUE THREAD

**Issue by lybgy** [purduesigbots/pros-docs#167]
Java is required for PROS. Please install the latest version of Java from http://java.sun.com/

mac os 10.15.2,has installed  java version ( 1.8.0_241-b07)

**Comment by HotelCalifornia** [comment]
What version of PROS do you have installed?

**Comment by lybgy** [comment]
V5(3.2.1)

**Comment by HotelCalifornia** [comment]
you can check by opening a command prompt and running `prosv5 --version`. if that command fails, check `pros --version`

**Comment by lybgy** [comment]
pros, version 2.6.1

**Comment by lybgy** [comment]
just now install for mac osx
pip3 install pros-cli
brew tap osx-cross/arm

**Comment by HotelCalifornia** [comment]
I'm going to close this as a non-issue. We don't support PROS 2.x anymore as PROS 3.x has full support for the cortex (and there is no java dependency)
