### ISSUE TITLE
"I2C Polling Tasks" and "Debugging Tips and Tricks" missing in I2C Communication Tutorial

### ISSUE THREAD

**Issue by MayorMonty** [purduesigbots/pros-docs#18]
![I2C Polling Tasks and Debugging Tips and Tricks missing in I2C Communication Tutorial on the PROS docs](https://cloud.githubusercontent.com/assets/8839926/23336303/c12f9574-fb99-11e6-9ced-f4a4684cff61.PNG)

Might it also be reasonable to list the static issues I've heard of? I don't know much, but I've heard that IMEs and I2C can be finicky in PROS

**Comment by edjubuh** [comment]
Closed by 245c38f
