### ISSUE TITLE
Some unrelated examples mislead in proper use of initialize, opcontrol and autonomous

### ISSUE THREAD

**Issue by nickmertin** [purduesigbots/pros-docs#191]
For example, the "Example" tab at: https://pros.cs.purdue.edu/v5/api/cpp/llemu.html#read-buttons

Which contains the following sample code:

```cpp
void initialize() {
  pros::lcd::initialize();
  while (true) {
    printf("Buttons Bitmap: %d\n", pros::lcd::read_buttons());
    delay(20);
  }
}
```

While this works for demonstration of the LLEMU API, it has lead some new users to mistakenly include while loops (such as this one verbatim) in the body of `initialize` within practical robot code, which as documented elsewhere, leads to bugs. I propose modifying this and all other similar examples to instead make proper separate use of `initialize` and `opcontrol`; for example:

```cpp
void initialize() {
  pros::lcd::initialize();
}

void opcontrol {
  while (true) {
    printf("Buttons Bitmap: %d\n", pros::lcd::read_buttons());
    delay(20);
  }
}
```

**Comment by HotelCalifornia** [comment]
Yeah it's definitely not correct
