### ISSUE TITLE
The multithreaded's synchronization section is wrong.

### ISSUE THREAD

**Issue by nathan-moore** [purduesigbots/pros-docs#213]
[This](https://pros.cs.purdue.edu/v5/tutorials/topical/multitasking.html#synchronization) section has the following code:
```c++
 int task1_variable = 0;
 void Task1(void * ignore) {
     // do things
     task1_variable = 4;
 }

 void Task2(void * ignore) {
   // do things
   // I can read task1_variable, but NOT write to it
   printf("%d\n", task1_variable);
 }
```

Which is wrong for at least 2 reasons. The c++ memory model makes no guarantees about the atomicity of accesses. There is also no compiler barriers that would prevent compiler hoisting (eg if they used this in a loop).

I see two solutions. The first would be to wrap task1_variable in a std::atomic. The concepts involved here are complicated and the solution is c++ only though. I'd personally recommend just deleting that section and recommending always using a mutex. They might have been trying to show case immutable data, which repurposing that section for that would also work.

**Comment by Octogonapus** [comment]
> The concepts involved here are complicated and the solution is c++ only though

I think atomics are simpler than a mutex. You just need to worry about reading/writing with the relevant methods, not about locking first, ensuring there is a corresponding unlock (not to mention doing that via RAII). Also, how would this solution be C++ only? These students also learn Java at this time, which has the same exact behavior WRT atomics.

**Comment by nathan-moore** [comment]
> Also, how would this solution be C++ only?

Compared to C. You can do similar with compiler intrinsics, but it exposes more gory details on what happens if the object can't be read atomically. Still an option I guess.
