### ISSUE TITLE
Filesystem tutorial sample code does not read or write to "example.txt"

### ISSUE THREAD

**Issue by SizzlinSeal01** [purduesigbots/pros-docs#253]
**What went wrong:**
If you copy the sample code in the filesystem doc (https://github.com/purduesigbots/pros-docs/blob/master/v5/tutorials/topical/filesystem.rst) it does not print values to an existing file or read values from an existing file. 

**What was expected**
For the sample code to print _Example text_ 

**Additional Information**
When you run the program once, it executes the code (I know because I made it print something to the brain screen after executing the sample code), although it does not read or write anything from the file as it does not output properly, and if If _example.txt_ was not created if it did not exist. You then exit the program and run it again, it never prints something to the brain screen, meaning that some line of code is blocking. _example.txt_ was also not manipulated at all (nothing was written in the file. Exiting and running the program for a third time restarts this cycle

**Comment by HotelCalifornia** [comment]
is the SD card formatted with FAT?

**Comment by WillXuCodes** [comment]
Might've been fixed with the proper renaming of the file handle.
