### ISSUE TITLE
Cquery is deprecated for Mac M2 / Arm

### ISSUE THREAD

**Issue by ray-** [purduesigbots/pros-docs#338]
Installing the editor via brew reveals this error:
```
==> Installing dependencies: cquery
Error: cquery has been disabled because it has an archived upstream repository!
```

From this [issue](https://github.com/Homebrew/homebrew-core/issues/90519#issuecomment-986291732)

> You can try installing homebrew with Rosetta (there's undoubtedly a lot of tutorials for this). But in the end this software has been abandoby the author and is going to stop working somewhere in the future. The only way forward is to find a replacement tool.

**Comment by ayushuk** [comment]
It seems you are trying to install the PROS editor. It was depreciated in favor of our [vscode extension](https://pros.cs.purdue.edu/v5/getting-started/index.html). Let me know if you have any more difficulties, we will update the docs to reflect this.
