### ISSUE TITLE
Hugo error for shortcodes/div.html when trying to build

### ISSUE THREAD

**Issue by Weastie** [purduesigbots/pros-docs#39]
```
ERROR: 2018/02/19 12:19:00 shortcode.go:533: error processing shortcode shortcodes/div.html

ERR: template: shortcodes/div.html:2:12: executing "shortcodes/div.html" at <markdownify>: wrong type for value; expected string; got template.HTML
```

This is the error I get when trying to build the project. I did not make any changes yet. It might be noteworthy that I am using Linux Mint 18.

I don't have a lot of experience with Hugo, so I am not sure how to handle this issue.

All of the nvm commands in build.sh work correctly.

**Comment by edjubuh** [comment]
What version of Hugo are you using? We've been using Hugo 0.19

**Comment by Weastie** [comment]
Yes, that fixed it!
