### ISSUE TITLE
Backend server does not use compression

### ISSUE THREAD

**Issue by Weastie** [purduesigbots/pros-docs#41]
I apologize if this is the wrong area to post this in.

The web server does not utilize gzip compression, which could make the site load significantly faster. I do not know what backend is used, but [Pagespeed Insights](https://developers.google.com/speed/docs/insights/EnableCompression) has a guide for ways to enable it on a few different servers.

**Comment by baylessj** [comment]
Just ran Pagespeed insights on the site, and it looks like there are some issues with the load time for sure, but the backend compression isn't one of them. 

I'll add a task to the team's internal bug tracker about minimizing HTML/CSS and prioritizing some javascript loading to see if that can accomplish more.
