### ISSUE TITLE
Motors C++ API docs - some function names don't match their prototypes

### ISSUE THREAD

**Issue by iuyte** [purduesigbots/pros-docs#45]
See title. In https://pros.cs.purdue.edu/v5/api/cpp/motors.html#get-target-position, the docs say it is `get_target_position`, but the prototype is
```Cpp
double pros::Motor::get_target ( )
```
and example is
```Cpp
void autonomous() {
  pros::Motor motor (1);
  motor.move_absolute(100, 100);
  std::cout << "Motor Target: " << motor.get_target();
  // Prints 100
}
```
Similar situation at https://pros.cs.purdue.edu/v5/api/cpp/motors.html#get-target-velocity, where it is shown to be `get_velocity` instead

**Comment by baylessj** [comment]
What kernel version are you using? `Motor::get_target` does not exist from what I can tell in 3.0.7, but `Motor::get_target_position` does.

**Comment by baylessj** [comment]
I'll go ahead and update the docs to have the prototypes be `Motor::get_target_position` and `Motor::get_target_velocity`, but I'm curious as to how `Motor::get_target` works for you.

**Comment by iuyte** [comment]
I'm not a beta tester ☹️, I was simply looking through the docs for V5 and noticed this.

**Comment by baylessj** [comment]
Ah my bad, I mistook the example code you posted as your own example code instead of that posted in the docs. I'll go ahead and fix this.
