### ISSUE TITLE
ChassisController tutorial is incomplete

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-docs#53]
The `ChassisController` tutorial [here](https://pros.cs.purdue.edu/v5/okapi/tutorials/concepts/chassiscontroller.html#how-can-i-make-a-chassiscontroller) is incomplete. It should at least continue by describing the gearset and scales after describing the motor configuration.

**Comment by baylessj** [comment]
Looks to me like the autonomous movement tutorial here: https://pros.cs.purdue.edu/v5/okapi/tutorials/walkthrough/autonomous-movement-basic.html covers most if not all of the follow up info about using a chassis controller, would it be reasonable to just link to that tutorial at the conclusion of this one?

**Comment by Octogonapus** [comment]
You're right, it does. I think we can just remove the chassis controller tutorial.

**Comment by baylessj** [comment]
Originally the purpose of the Chassis Controller tutorial was to help explain the difference between a Chassis Controller using the onboard PID and one using Okapi's PID, do you think that still merits its own tutorial? I don't think that topic is covered elsewhere.

**Comment by Octogonapus** [comment]
Sure, if it's not covered, I suppose there could be a short page on that.
