### ISSUE TITLE
Add real documentation about uploading

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros-docs#67]
Currently there's nothing, and there should probably be something.

Once interactive UI is done (CLI/middleware/atom plugin) we should take screenshots and stuff.

**Comment by HotelCalifornia** [comment]
TODO: other relevant documentation relating to PROS Editor

**Comment by kunwarsahni01** [comment]
https://pros.cs.purdue.edu/v5/tutorials/walkthrough/uploading.html This link is currently on the  [First Time Users Guide](https://pros.cs.purdue.edu/v5/getting-started/new-users.html) and it leads nowhere, presuming that means that uploading documentation still needs to be made if so I can get on that.
