### ISSUE TITLE
Man Page for CLI + Sphinx Docs

### ISSUE THREAD

**Issue by seendsouza** [purduesigbots/pros-docs#78]
I was thinking of making a man page for prosv5 (CLI), but I saw that you were using Sphinx for your docs. Sphinx has a feature where you can make man pages from your Sphinx documentation (http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output), so I was wondering how we should go about approaching making the man page (making a sphinx page for prosv5 cli in the pros-docs repo and transferring the sphinx generated man page to pros-cli, or just making the man page from scratch)

**Comment by edjubuh** [comment]
I'm fine with either solution, although generating man pages from sphinx output sounds more appealing to me since it sounds like Sphinx does a lot of the work for you.

**Comment by Octogonapus** [comment]
I second having Sphinx generate the man page.

**Comment by kunwarsahni01** [comment]
Since were moving to Doxygen should be pretty straightforward to generate the man page from there.
