### ISSUE TITLE
Clawbot Tutorial Extension

### ISSUE THREAD

**Issue by seendsouza** [purduesigbots/pros-docs#79]
I was wondering if you thought if it would be a good idea to initialize the motors in their own file and declare them in a header file using extern in the clawbot tutorial, since it lets the autonomous also access those motors. In addition, I was wondering if we could add a simple autonomous for the clawbot to showcase motors not only moving using move_velocity and move, but maybe something like move_relative. For Arcade Control, my team calls that split arcade control (two joysticks), whereas arcade control (one joystick) would be something like this:
```
int power = master.get_analog(ANALOG_LEFT_Y);
int turn = master.get_analog(ANALOG_LEFT_X);
int left = power + turn;
int right = power - turn;
left_wheels.move(left);
right_wheels.move(right);
```
I was wondering if we could rename it to split arcade, unless it is generally called arcade (or we could add both).

**Comment by HotelCalifornia** [comment]
> I was wondering if you thought if it would be a good idea to initialize the motors in their own file and declare them in a header file using extern

Why? There's no need to do this as you can declare motors locally whenever you need them.

None of the objects the PROS API exposes have any internal state that might require them to be global (all the objects do is wrap a port number, and any device configuration is passed off to vexOS). I understand that a lot of people like to go this route, but my feeling is that it's out of the scope of the tutorial.

> In addition, I was wondering if we could add a simple autonomous for the clawbot to showcase motors not only moving using move_velocity and move, but maybe something like move_relative.

Good idea. We can do that.

> For Arcade Control, my team calls that split arcade control

I've seen the term "split arcade" used enough that I think this would be okay as well. (Though maybe @baylessj has more to say on that)

**Comment by seendsouza** [comment]
For the first one, do you think we should make a different page talking about both the routes (extern vs locally).
For the autonomous, should I make it just drive straight?
